### ISSUE TITLE
issue with README instructions

### ISSUE THREAD

**Issue by gthaka** [jkariscodes/nairobi-busstops#20]
I came across the issue while following the Docker instructions for setting up the project. 

See attached screenshot.

![image](https://github.com/jkariscodes/nairobi-busstops/assets/6692971/155d3261-0992-47fb-bfb8-c12e8eea0eaa)

I had cloned the project previously and I will be sending a PR of the possible correction.

Thanks.

**Comment by jkariscodes** [comment]
Thanks. I missed this. Let me create a fix for it.

**Comment by jkariscodes** [comment]
Fixed at #21
